### ISSUE TITLE
Include github actions `runs-on` field in key.

### ISSUE THREAD

**Issue by rukai** [Swatinem/rust-cache#45] opened 2022-02-09 02:22 UTC
I just hit a confusing compilation issue when downgrading from `runs-on: ubuntu-20.04` to `runs-on: ubuntu-18.04` caused because the cache didnt clear.
I'm not sure if you have access to this field, maybe something similar could be done by looking at something like `lsb_release -a`

**Comment by jessestricker** [comment] 2022-10-17 22:10
I am not sure if this is related, but I get this error on my workflow:

```
error: failed to select a version for the requirement `clap = "=4.0.15"`
candidate versions found which didn't match: 3.2.22, 3.2.21, 3.2.20, ...
location searched: crates.io index
```

I run the job with the following matrix:

```yaml
rust-version: ["1.56", stable]
runner: [ubuntu-latest, macos-latest]
```

Locally, building works with both versions with a clean cache.

**Comment by rukai** [comment] 2022-10-17 22:15
I think that is unrelated to this issue, your issue is to do with dependency resolution while this issue is caused by different versions of ubuntu having different versions of external c/c++ dependencies.

I suspect the difference in behavior you are experiencing is due to your local Cargo.lock file.
Try deleting that and seeing if you can reproduce the problem locally that way.
I'm just guessing from the error message, but if you have set `clap = "=4.0.15"` that can cause all sorts of problems with dependency resolution and you would be better off specifying it as just `clap = "4.0.15"`.

**Comment by jessestricker** [comment] 2022-10-17 22:35
Thanks for your suggestions.

> I suspect the difference in behavior you are experiencing is due to your local Cargo.lock file.
Try deleting that and seeing if you can reproduce the problem locally that way.

I have the same `Cargo.lock` file committed to the repo for reproducibility, so it should work in both CI and local. Also I run `cargo` with the `--locked` flag in CI.

> you would be better off specifying it as just `clap = "4.0.15"`

I do actually specify the dependency as `clap = { version = "4.0.15", features = ["derive"] }`. I suspect the constrain on `=4.0.15` is because that's the version in the `Cargo.lock` file as well.

**Comment by tgnottingham** [comment] 2024-06-27 18:30
I encountered this issue when upgrading from a 20.04 runner to a 22.04 runner. The former has OpenSSL v1, while the latter has OpenSSL v3. When building on 22.04, it appeared that the cached results of the `openssl-sys` crate from 20.04 were being used at link time, as the build complained about references to undefined symbols, which as it turns out were ones removed from OpenSSL between v1 and v3.

It was fairly difficult to track down the root cause of this, so I suspect that it may be hitting more people than one would think given the activity on this thread.

**Comment by rnbguy** [comment] 2024-11-29 15:21
Just stumbled upon this issue. ubuntu runner tried to restore a partial key -- which happened to be for macos.

**Closed** 2024-12-09 21:32 UTC
